import { useContext } from "react";
import Head from "next/head";
import Link from "next/link";
import styles from '../styles/Home.module.css';

import themeContext from "./themeContext";

const Navbar = () => {
    const { toggleTheme, theme } = useContext(themeContext);
    const newThemeName = theme === "dark" ? "light" : "dark";

    return (
        <div style={{
            display: "flex",
            flexDirection: "row",
            justifyContent: "space-between",
            marginBottom: 25
        }}>
            <div className={styles.container}>
                <Head>
                    <title>Learn Next JS</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <div>
                    <Link href='/' prefetch={false}><a>Home</a></Link>
                    <Link href='/about' prefetch={false}><a>About</a></Link>
                    <Link href='/contacts' prefetch={false}><a>Contacts</a></Link>
                    <Link 
                        href={{
                            pathname: '/posts/[date]/[slug]',
                            query: {
                                date: '2023-01-01',
                                slug: 'happy-new-year',
                                foo: 'bar'
                            }
                        }}  
                    >
                        <a>Read This Post</a>
                    </Link>
                    
                    <button onClick={toggleTheme}>
                        Set {newThemeName} theme
                    </button>

                </div>
            </div>
        </div>
        
    )
}

export default Navbar;