import { useRouter } from 'next/router';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../../styles/Home.module.css';

const Greet = () => {
    const { query } = useRouter();
    console.log(query);

  return (
    <div className={styles.container}>
      <Head>
        <title>Greet Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hello, {query.name}!
        </h1>


        <div className={styles.grid}>
          
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="#"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '} Jeff

        </a>
      </footer>
    </div>
  )
}

export default Greet;
