import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const ContactPage = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Learn Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          This is Contact Page
        </h1>


        <div className={styles.grid}>
          <ul>
            <li>
              Email: jeffersongakuya@gmail.com
            </li>
            <li>
              Twitter: @iamgakuya
            </li>
            <li>
              Instagram: @iamgakuya
            </li>
          </ul>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="#"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '} Jeff

        </a>
      </footer>
    </div>
  )
}

export default ContactPage;